---
name: vizier-release
on:
  push:
    tags:
    - release/vizier/**
permissions:
  contents: read
env:
  VERSIONS_FILE: "VERSIONS.json"
jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p "artifacts/"
        echo "test" > artifacts/my_artifact
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce  # v3.1.2
      with:
        name: vizier-artifacts
        path: artifacts/
  create-github-release:
    name: Create Release on Github
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3  # v3.5.0
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a  # v3.0.2
    - name: Create Release
      env:
        REF: ${{ github.event.ref }}
        GH_TOKEN: ${{ secrets.BUILDBOT_GH_API_TOKEN }}
        OWNER: JamesMBartlett
        REPO: pixie
      shell: bash
      # yamllint disable rule:indentation
      run: |
        export TAG_NAME="${REF#*/tags/}"
        # actions/checkout doesn't get the tag annotation properly.
        git fetch origin tag "${TAG_NAME}" -f
        export changelog="$(git tag -l --format='%(contents)' "${TAG_NAME}")"
        gh release create "${TAG_NAME}" --title "Vizier ${TAG_NAME#release/vizier/}" \
          --notes $'Pixie Vizier Release:\n'"${changelog}"
        gh release upload "${TAG_NAME}" vizier-artifacts/*
      # yamllint enable rule:indentation
